USE CondorTest;
INSERT INTO `user_profile`(`id_user`, `nm_first`, `nm_middle`, `nm_last`) VALUES (1,'rafa','andres','rocha');
INSERT INTO `user_profile`(`id_user`) VALUES (2);
INSERT INTO `user_profile`(`id_user`, `nm_first`) VALUES (3,'jose');
INSERT INTO `user_profile`(`id_user`, `nm_last`) VALUES (4,'barrios');
INSERT INTO `user_profile`(`id_user`, `nm_middle`) VALUES (5,'maria');
INSERT INTO `user_profile`(`id_user`) VALUES (6);
INSERT INTO `user_profile`(`id_user`, `nm_first`) VALUES (7,'jose');
INSERT INTO `user_profile`(`id_user`, `nm_last`) VALUES (8,'barrios');
INSERT INTO `user_profile`(`id_user`, `nm_middle`) VALUES (9,'maria');
INSERT INTO `user_profile`(`id_user`, `nm_middle`) VALUES (10,'maria');
INSERT INTO `user_address`(`id_address`, `id_user`) VALUES (1,1);
INSERT INTO `user_address`(`id_address`, `id_user`) VALUES (2,2);
INSERT INTO `user_address`(`id_address`, `id_user`) VALUES (3,3);
INSERT INTO `user_address`(`id_address`, `id_user`) VALUES (4,4);
INSERT INTO `user_address`(`id_address`, `id_user`) VALUES (5,5);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (1,'LICENSEE',1,1);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (2,'LIMITED',2,1);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (3,'LICENSEE',3,0);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (4,'LIMITED',4,0);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (5,'LICENSEE',5,1);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (6,'LICENSEE',6,1);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (7,'PROVIDER',7,0);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (8,'PROVIDER',8,0);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (9,'PROVIDER',9,0);
INSERT INTO `user_role`(`id_user`, `cd_role_type`, `id_entity`, `in_status`) VALUES (10,'PROVIDER',10,1);
